### ISSUE TITLE
issue to run on mac

### ISSUE THREAD

**Issue by jerryum** [ganeshsar/UnityPythonMediaPipeBodyPose#4]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/jerrylee/Works/UnityPythonMediaPipeAvatar/mediapipeavatar/body.py", line 93, in run
    cv2.imshow('Body Tracking', image)
cv2.error: Unknown C++ exception from OpenCV code

When I run main.py, I got this error message. pose landmarks are captured and Avatar are moving but the video stream can't be shown.  This is on MacOS and  Python 3.10. Keep debugging but it's to let you know. 

By the way, the "sample scene" in the Readme is gone, and found calibrationScene. Could you update readme? 

Thank you for the project.

**Comment by ganeshsar** [comment]
I will update the readme, thanks for letting me know.
Also could you try: https://github.com/ganeshsar/UnityPythonMediaPipeAvatar

It uses sockets rather then pipes which should make it support mac, but I need someone with a mac to test.

EDIT: Wait, looks like you were using the Avatar project already. I will look more into this.

**Comment by ganeshsar** [comment]
Have you tried changing WEBCAM_INDEX in global_vars.py?
